# Top-level configuration
account_id = "852dfa4ae1b0d579df29be65b986c101"
name = "helix-snapshot-scheduler-prod"
main = "src/index.js"
compatibility_date = "2023-05-05"

[[kv_namespaces]]
binding = "SCHEDULER_KV"
id = "11afb687a55f4cb29bcba5e50e1754a2"
preview_id = "bbd7a7c511834e80875bda0c6bcc43c2"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'helix-snapshot-scheduler'
preview_bucket_name = 'helix-snapshot-scheduler-ci'

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true