# Top-level configuration
account_id = "852dfa4ae1b0d579df29be65b986c101"
name = "helix-snapshot-scheduler-snapshot-publish-ci"
main = "src/index.js"
compatibility_date = "2023-05-05"

[[queues.consumers]]
queue = "helix-snapshot-scheduler-publish-ci"

[observability]
enabled = true