name: build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
jobs:
  test_ci_deploy:
    name: Test, Deploy to CI environment and test Post-Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [publish, cron, register, dlq]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies for ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm ci
    - name: Lint ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm run lint
    - name: Unit Test ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm run test || echo "No tests configured yet"

    # Deploy to CI environment
    - name: Deploy ${{ matrix.worker }} to CI
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_KEY }}
      run: cd ${{ matrix.worker }} && npm run deploy-ci
    
    # Wait for deployment to propagate
    - name: Wait for ${{ matrix.worker }} service update
      run: sleep 30
    
    # Run post-deployment tests
    - name: Post-Deployment Integration Test ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm run test-postdeploy || echo "Post-deployment tests skipped"
    
    # Upload coverage if tests exist
    - name: Upload coverage to Codecov for ${{ matrix.worker }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ matrix.worker }}/coverage/lcov.info
        fail_ci_if_error: false