name: Semantic Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [publish-snapshot, tenant-poll]
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies for ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm ci
    - name: Semantic Release for ${{ matrix.worker }}
      run: cd ${{ matrix.worker }} && npm run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CORALOGIX_TAGGER_API_KEY: ${{ secrets.CORALOGIX_TAGGER_API_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        # Deployment variables
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_KEY }}